dist: xenial
language: python
python:
- '3.6'
services:
- docker
env:
  global:
    - ENVIRONMENT=ci
    - BASE_FOLDER=$TRAVIS_BUILD_DIR
before_install:
- sudo apt-get install -y libmysqlclient-dev
addons:
  apt:
    update: true
install:
- pip3 install -r tests/requirements-test.txt
before_script:
- scripts/docker-compose-provision.sh $ENVIRONMENT $BASE_FOLDER
script:
- tests/wait_mysql_up.sh
- sleep 15
- tests/is_table_empty.py
- tests/basic_http_get_test.py
- flake8 --exclude venv .
