---
dist: xenial

language: python

python:
  - "3.6"

services:
  - docker

install:
  - pip install -r test-requirements.txt
  - docker build -t devopsloft/devopsloft --build-arg REQUIREMENTS=requirements-dev.txt docker/.

before_script:
  - docker run -d -p 80:80 --name web devopsloft/devopsloft
  - docker cp tests web:/tests/
  - docker exec -it web bash -c 'pip install pyyaml'

script:
    - flake8 --exclude venv .
    - docker exec -it web bash -c 'python3 /tests/is_table_empty.py'
    - docker exec -it web bash -c 'python3 /tests/basic_http_get_test.py'
