dist: xenial

language: python

python:
- '3.6'

services:
- docker

env:
  global:
    - ENVIRONMENT=ci
    - BASE_FOLDER=$TRAVIS_BUILD_DIR
    - WEB_HOST_PORT=5000
    - WEB_GUEST_PORT=5000
    - WEB_HOST_SECURE_PORT=8443
    - WEB_GUEST_SECURE_PORT=8443

before_install:
- sudo apt-get install -y libmysqlclient-dev

addons:
  apt:
    update: true

install:
- pip install -r tests/requirements-test.txt

before_script:
- openssl req -x509 -newkey rsa:4096 -nodes -out web_s2i/cert.pem -keyout web_s2i/key.pem -days 365 -subj "/C=IL/ST=Gush-Dan/L=Tel-Aviv/O=DevOps Loft/OU=''/CN=''"
- scripts/docker-compose-provision.sh $ENVIRONMENT $BASE_FOLDER $WEB_HOST_PORT $WEB_GUEST_PORT $WEB_HOST_SECURE_PORT $WEB_GUEST_SECURE_PORT

script:
- tests/wait_mysql_up.sh
- sleep 15
- tests/is_table_empty.py
- tests/basic_http_get_test.py
- flake8 --exclude venv .
