dist: xenial
language: python
python:
- '3.6'
services:
- docker
env:
- ENVIRONMENT=ci
before_install:
- sudo apt-get install -y libmysqlclient-dev
addons:
  apt:
    update: true
install:
- pip3 install -r tests/requirements-test.txt
before_script:
- docker-compose -f docker-compose.yml up -d --build --force-recreate
- scripts/vault-init.sh .
script:
- tests/wait_mysql_up.sh
- sleep 15
- tests/is_table_empty.py
- tests/basic_http_get_test.py
- flake8 --exclude venv .
