version: "3.7"
services:
  db:
    image: ${APP}/${DOCKERHUB_DB}
    build: ./db_s2i
    container_name: db
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    ports:
      - 3306:${MYSQL_PORT}
    restart: always

  web:
    image: ${APP}/app
    build: ./web_s2i
    container_name: web
    ports:
      - 80:${APP_GUEST_PORT}
    restart: always

  vault:
    image: ${APP}/vault
    container_name: vault
    build:
      context: ./vault_s2i
      args:
        VAULT_GUEST_PORT: ${VAULT_GUEST_PORT}
    ports:
      - 8200:${VAULT_GUEST_PORT}
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
