---
- name: Deploy Software
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - role: geerlingguy.mysql
    - role: realsalmon.mysql-client

  tasks:

    - name: Create database
      mysql_db:
        state: import
        name: all
        target: "{{ playbook_dir }}/create_db.sql"
